### ISSUE TITLE
Don't commit library files

### ISSUE THREAD

**Issue by damithc** [whneo97/duke#4]
It's not usual for library files to be committed to the repo. Your repo seems to have lot of .md files from a third-party library

**Comment by whneo97** [comment]
Hi prof, thank you for the feedback! I'm not too sure where exactly the problem lies but I suspect it could be due to the javafx folder in my duke project directory, which does appear contain a few .md files (other than this, I don't seem to see any other third-party libraries in my repository). 

I have removed the javafx folder from my repository along with a Photoshop file used for the background image of my GUI in my latest commit.

Does the problem happen to still remain?

**Comment by damithc** [comment]
Yes, it's the javafx folder that was causing a distortion in the iP code dashboard. Thanks for removing it.

**Comment by whneo97** [comment]
> Yes, it's the javafx folder that was causing a distortion in the iP code dashboard. Thanks for removing it.

Okay noted, thank you prof!
